name: Cleanup PR Preview
on:
  pull_request:
    types:
      - closed

jobs:
  destroy-dev:
    runs-on: ubuntu-latest
    env:
      BUILD_ENV: dev
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'yarn'

      - name: Build lambda code
        run: |
          yarn install:ci
          yarn build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHub_Actions_Role
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./terraform
        run: make init

      - name: Destroy Dev Resources
        working-directory: ./terraform
        run: make destroy ARGS="-auto-approve"
